# Resource: 
# - https://www.baeldung.com/ops/kafka-docker-setup
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: apxkfk_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    #volumes: 
    #  - ./volumes/data/zookeeper:/var/lib/zookeeper/data
    #  - ./volumes/log/zookeeper:/var/lib/zookeeper/log    
    networks:
      apisix:
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: apxkfk_kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: apxkfk_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://apxkfk_kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #volumes: 
    #  - ./volumes/data/kafka:/var/lib/kafka/data 
    networks:
      apisix:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: apxkfk_kafka_ui
    
    depends_on:
      - kafka
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: kafka-dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: apxkfk_kafka:9092
      #SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
    networks:
      apisix:
    
networks: 
  apisix:
    external: true
    name: example_apisix
    